version: '3'

services:
  front-dev-app:
    container_name: coias-front-dev-container
    build:
      context: ./coias-front-app/
      dockerfile: ./Docker/Dockerfile.dev
    image: coias-front-dev-app
    ports:
      - 127.0.0.1:3000:3000
    tty: true
    platform: linux/x86_64
    volumes:
      - ./coias-front-app/:/opt/coias-front-app
      - node_modules_volume:/opt/coias-front-app/node_modules

  back-dev-app:
    container_name: coias-back-dev-container
    build:
      context: ./coias-back-app/
      dockerfile: ./Docker/Dockerfile.dev
    image: coias-back-dev-app
    ports:
      - 127.0.0.1:8000:8000
    tty: true
    platform: linux/x86_64
    volumes:
      - ./coias-back-app:/opt/coias-back-app
      - nginx_tmp_images:/opt/tmp_images
      - coias_hsc:/root/.coias

  imagehost-dev-app:
    image: "nginx:latest"
    ports:
      - "8088:80"
    volumes:
      - "nginx_tmp_images:/usr/share/nginx/html"
      - "./nginx:/etc/nginx"

volumes:
  node_modules_volume:
  nginx_tmp_images:
  coias_hsc: