version: '3'

services:
  front-dev-app:
    container_name: coias-front-dev-container
    build:
      context: ./coias-front-app/
      dockerfile: ./Docker/Dockerfile.dev
    image: coias-front-dev-app
    ports:
      - 127.0.0.1:3000:3000
    tty: true
    volumes:
      - ./coias-front-app:/opt/coias-front-app

  back-dev-app:
    container_name: coias-back-dev-container
    build:
      context: ./COIAS_program_github/
      dockerfile: ./Docker/Dockerfile.dev
    image: coias-back-dev-app
    ports:
      - 127.0.0.1:8000:8000
    tty: true
    volumes:
      - ./COIAS_program_github:/opt/COIAS_program_github
      - ./COIAS_program_github/SubaruHSC:/opt/SubaruHSC
      - ./COIAS_program_github/data:/root/.coias

  imagehost:
    image: "nginx:latest"
    volumes:
      - "./COIAS_program_github/SubaruHSC:/usr/share/nginx/html"
      - "./nginx:/etc/nginx"
    ports:
      - "8088:80"