version: '3'

services:
  front-app:
    container_name: coias-front-container
    build:
      context: ./coias_electron/
      dockerfile: ./Docker/Dockerfile
    image: coias-front-app
    ports:
      - 127.0.0.1:3000:3000

  back-app:
    container_name: coias-back-container
    build:
      context: ./COIAS_program_github/
      dockerfile: ./Docker/Dockerfile
    image: coias-back-app
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./COIAS_program_github/SubaruHSC:/opt/SubaruHSC
      - ./COIAS_program_github/data:/root/.coias
