version: "3"

services:
  front-dev-app:
    container_name: coias-front-dev-container
    build:
      context: ./web-coias-front-app
      dockerfile: ./Dockerfile.dev
    image: coias-front-dev-app
    ports:
      - 127.0.0.1:3000:3000
    tty: true
    platform: linux/x86_64
    volumes:
      - ./web-coias-front-app/:/opt/web-coias-front-app:delegated
      - app_node_modules_volume:/opt/web-coias-front-app/node_modules

  front-dev-page:
    container_name: coias-front-page-dev-container
    build:
      context: ./web-coias-front-page
      dockerfile: ./Dockerfile.dev
    image: coias-front-page-dev-app
    ports:
      - 127.0.0.1:3001:3001
    tty: true
    platform: linux/x86_64
    volumes:
      - ./web-coias-front-page/:/opt/web-coias-front-page:delegated
      - page_node_modules_volume:/opt/web-coias-front-page/node_modules

  back-dev-app:
    container_name: coias-back-dev-container
    build:
      context: ./web-coias-back-app
      dockerfile: ./Dockerfile.dev
    image: coias-back-dev-app
    ports:
      - 127.0.0.1:8000:8000
    tty: true
    platform: linux/x86_64
    volumes:
      - ./web-coias-back-app:/home/COIASusers/web-coias-back-app
      - nginx_tmp_images:/home/COIASusers/tmp_images
      - coias_hsc:/root/.coias

  imagehost-dev-app:
    image: "nginx:latest"
    ports:
      - "8088:80"
    volumes:
      - "nginx_tmp_images:/usr/share/nginx/html"
      - "./imagehost/nginx:/etc/nginx"

  mysql:
    container_name: coias-mysql
    image: mysql:5.7
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: COIAS
      MYSQL_USER: dataHandler
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  keycloak:
    container_name: coias-keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: coiaskeycloak
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  nginx_tmp_images:
  app_node_modules_volume:
  page_node_modules_volume:
  coias_hsc:
  mysql_data:
    driver: local
